import Head from 'next/head'
import React, { FunctionComponent } from 'react'
import { Header } from './Header'
import CookieConsent from "react-cookie-consent";
import Link from 'next/link';

interface Props {

}

export const Layout: FunctionComponent<Props> = ({ children }) => {
    return (
        <div style={{ height: "100%" }}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="initial-scale=1, width=device-width" />
                <link rel="icon" href="/favicon.ico" />
            </Head>


            <Header />
            {children}

            <CookieConsent
                location="bottom"
                buttonText="Sprejmi"
                cookieName="privolitev"
                style={{ background: "#386A7A" }}
                buttonStyle={{ color: "#4e503b", fontSize: "13px"}}
                expires={150}
            >
                Spletni portal Ministerstva za zunanje zadeve uporablja piškotke za zagotavljanje spletne storitve. 
                S klikom na gumb »Sprejmi« soglašate z uporabo piškotkov. Izjavo o zasebnosti in varnosti podatkov si lahko preberete <a href={"/privacyStatement"} style={{color: "#E5FF00"}}>tukaj</a>.  
            </CookieConsent>
        </div>
    )
}
