import Head from 'next/head'
import React, { FunctionComponent } from 'react'
import { Header } from './Header'

interface Props {

}

export const Layout: FunctionComponent<Props> = ({ children }) => {
    return (
        <div style={{height: "100%"}}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="initial-scale=1, width=device-width" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            
            <Header/>
            {children}
        </div>
    )
}
